language: cpp

compiler:
  - clang
  - gcc

os:
  - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost1.58-dev

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cd ..
  - make VERBOSE=1
