#sudo: required
#dist: trusty

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux

before_install:
  - sudo apt-get install debian-archive-keyring
  - sudo apt-key update
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-dev

addons:
  apt:
    sources:
    - boost-latest

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cd ..
  - make VERBOSE=1
